### ISSUE TITLE
support unload hv 

### ISSUE THREAD

**Issue by alienwu2018** [jonomango/hv#1]
hello teacher，sometime i just use hv for a minute，so i hope hv can support unload hypervistor instead of reboot system

**Comment by jonomango** [comment]
This shouldn't be too difficult to implement, although a lot of code will need to be reworked. I'll try to get it added by tomorrow.

**Comment by alienwu2018** [comment]
thanks teacher！

**Comment by jonomango** [comment]
I added `hv::stop()` in https://github.com/jonomango/hv/commit/649a694acedad668f091590f5ecfb9e76aa1c06f for devirtualizing the system. This will automatically get called on driver unload and is good for rapid testing. Let me know if you encounter any issues.

**Comment by alienwu2018** [comment]
yeach!I rebuild this version today and i try it many times. I can&nbsp;&nbsp;stop the hv and&nbsp;devirtualizing the system successfully in winver 21h2.Thanks teacher very much.(●'◡'●)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月16日(星期一) 上午10:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jonomango/hv] support unload hv  (Issue #1)





 
I added hv::stop() in 649a694 for devirtualizing the system. This will automatically get called on driver unload and is good for rapid testing. Let me know if you encounter any issues.
