### ISSUE TITLE
Vmlaunch is failing on a new cpu

### ISSUE THREAD

**Issue by thewolfram** [jonomango/hv#13]
hey jonomango, I've got a new i5-12400F cpu and when I start the hypervisor, it is failing with instruction error 7
![image](https://user-images.githubusercontent.com/66202986/217552586-e5ab5726-d180-4239-ac65-1c731cb849a4.png)

**Comment by jonomango** [comment]
This is the second time I've seen this issue and I'm still not sure what the cause is. According to the Intel Manual, error 7 means "VM entry with invalid control field." Try commenting out [this line](https://github.com/jonomango/hv/blob/main/hv/timing.h#L5) and seeing what happens.

**Comment by thewolfram** [comment]
> This is the second time I've seen this issue and I'm still not sure what the cause is. According to the Intel Manual, error 7 means "VM entry with invalid control field." Try commenting out [this line](https://github.com/jonomango/hv/blob/main/hv/timing.h#L5) and seeing what happens.

I tried, but still nothing changed

**Comment by jonomango** [comment]
Can you try to set [this line](https://github.com/jonomango/hv/blob/main/hv/vmcs.cpp#L51) to 0?

**Comment by thewolfram** [comment]
> Can you try to set [this line](https://github.com/jonomango/hv/blob/main/hv/vmcs.cpp#L51) to 0? 

I did this and now my pc is straight freezing without bsod

**Comment by jonomango** [comment]
Interesting, I'll have to push a commit with that fix. I'm already aware that the hypervisor doesn't work correctly for Intel 10th gen and up, which can be seen in [this issue](https://github.com/jonomango/hv/issues/9) so I'll mark this as closed for now since we fixed the original issue.

**Comment by thewolfram** [comment]
> Interesting, I'll have to push a commit with that fix. I'm already aware that the hypervisor doesn't work correctly for Intel 10th gen and up, which can be seen in [this issue](https://github.com/jonomango/hv/issues/9) so I'll mark this as closed for now since we fixed the original issue.

It actually works for 10th gen Intel, you can see [my issue](https://github.com/jonomango/hv/issues/8) where you helped me.

**Comment by jonomango** [comment]
Sorry, I meant 11th gen and up 😅

**Comment by jonomango** [comment]
I think that I'll try to compile a list of every Intel CPU that the hypervisor is confirmed to work on since it just seems to fail on the newer ones.

**Comment by jonomango** [comment]
Initial issue is fixed with https://github.com/jonomango/hv/commit/7ea88187afe2aac49151654e5c418c961b7bb94c

**Comment by jonomango** [comment]
As for the crashes, some users have said that increasing https://github.com/jonomango/hv/blob/main/hv/ept.h#L10 to around ~512 has fixed the issue, probably due to some I/O devices claiming the physical memory above RAM (my hypothesis).
