### ISSUE TITLE
Win10 19041 (2004) Freezing PC

### ISSUE THREAD

**Issue by lhaasper** [jonomango/hv#14]
So yea, log looks just like the log shown here https://github.com/jonomango/hv/issues/12 no errors or nothing

Fully freezing PC no BSOD, nothing

**Comment by jonomango** [comment]
Maybe try this? https://github.com/jonomango/hv/issues/13#issuecomment-1429118423 There happens to be a lot of missing error checking that I’ll have to sort out to atleast ensure a graceful bluescreen instead of freezing.

**Comment by lhaasper** [comment]
Interestingly with ept_pd_count set to 512 it seems to be loading correctly
