### ISSUE TITLE
fix timing measure bug

### ISSUE THREAD

**Issue by wercfz** [jonomango/hv#15]
I found a bug in time measure. Because once nmi occurs, the value of adjust will become very small. As a result, the hide overhide becomes incorrent.
  The following is fixed code.
    //auto const adjusted = (vm_exit_overhead - timing_overhead);

    /*if (adjusted < lowest) {
        lowest = adjusted;
    }*/
    if (vm_exit_overhead < lowest_vm_exit_overhead) {
        lowest_vm_exit_overhead = vm_exit_overhead;
    }
    if (timing_overhead < lowest_timing_overhead) {
        lowest_timing_overhead = timing_overhead;
    }
    lowest = (lowest_vm_exit_overhead - lowest_timing_overhead);

**Comment by jonomango** [comment]
fixed in https://github.com/jonomango/hv/commit/70210e2113a2ea634c8bfbaea312b39880f1e265
