### ISSUE TITLE
[Not an issue] Resources for developing a hypervisor?

### ISSUE THREAD

**Issue by chiefmasterR** [jonomango/hv#26]
I'd like you to recommend resources and books for learning about the Intel hypervisor and developing it. The only ones I know of are Intel's SDM and the Daax "5 days to virtualization" series.

**Comment by jonomango** [comment]
intel manual
https://howtohypervise.blogspot.com/
http://standa-note.blogspot.com/
https://rayanfam.com/topics/hypervisor-from-scratch-part-1/
intel manual
https://github.com/Wenzel/awesome-virtualization
any hypervisor-related posts by pyro666, daax, or namazso on unknowncheats
https://github.com/Zero-Tang/NoirVisor/blob/master/src/vt_core/readme.md
https://git.back.engineering/_xeroxz/bluepill
intel manual is good too
