### ISSUE TITLE
mmr logging bug

### ISSUE THREAD

**Issue by chiefmasterR** [jonomango/hv#33]
https://github.com/jonomango/hv/blob/86ca9f50238c65b75ef04fdec1f6c45d8e98fdbf/hv/exit-handlers.cpp#L573

I think you forgot to check for `is_relevant_mode`, I think it should be this way: `if (physical_address >= entry.start && physical_address < (entry.start + entry.size) && is_relevant_mode)`

**Comment by jonomango** [comment]
Good catch. I fixed this on my local repository but forgot to push the changes.

**Comment by jonomango** [comment]
https://github.com/jonomango/hv/commit/cd4d4022351b5d762045a02108973c697a79bb34
