### ISSUE TITLE
doc or demo for hypercalls.h

### ISSUE THREAD

**Issue by LYingSiMon** [jonomango/hv#34]
I really need it 🤣，Hope you can join an example project to teach us how to use these interfaces.

**Comment by jonomango** [comment]
Have you looked at the `um` project that is in this repository, as well as https://github.com/jonomango/hv/blob/main/um/hv.h#L77-L131? I think those should be enough to understand how to use the hypercalls.

**Comment by LYingSiMon** [comment]
// install an EPT hook for the CURRENT logical processor ONLY
bool install_ept_hook(uint64_t orig_page_pfn, uint64_t exec_page_pfn);

I don't quite understand this function.

If I hook NtCreateFile, I should return an OrigFunction pointer inside the HookNtCreateFile,  how can i use install_ept_hook to hook NtCreateFile?

**Comment by jonomango** [comment]
You will need to use something similar to inline hooking, except instead of writing directly to the original function, you'll be writing to the executable page that is installed with `install_ept_hook()`.
