### ISSUE TITLE
i need hv support ept hook

### ISSUE THREAD

**Issue by alienwu2018** [jonomango/hv#4]
can give me an example?

**Comment by jonomango** [comment]
@alienwu2018 Sure. I call it an "EPT hook" in the source, but it's better to think of it as just splitting a physical page into two separate pages. One gets used when the page is being read/written to, and the other gets used whenever code is being executed. This lets us execute code that is different from what is being read, which is very useful for bypassing integrity checks.

Awhile back, I wrote a quick-and-dirty [example of using EPT hooks to globally hook syscalls](https://github.com/jonomango/hv/blob/02dec7ccd1ec491925fdde0753c5eac1ab99810f/hv/main.cpp). The code is a bit old, and the hypercall interface may have changed in that time, but it should show the general idea of how to use it. All you do is provide the physical addresses of two pages. The first "original" page is the page that we'll be hooking and that all reads and writes will use, while the second page is the executable page where code will be executed from.

I hope this helps. Feel free to ask any more questions. 👍

**Comment by alienwu2018** [comment]
thanks!
