### ISSUE TITLE
Can I ask you some questions?

### ISSUE THREAD

**Issue by LYingSiMon** [jonomango/hv#41]
hello jonomango.

I've been studying VT knowledge recently, so I've been reading your code, and there's something that confuses me. In 'hide_physical_page()', you use 'pte->page_frame_number = cpu->ept.dummy_page_pfn;' to write the dummy page into the PTE. However, why is 'pte->read_access=0' not set here so that the next access triggers 'handle_ept_violation'? If not, how do you intercept read memory behavior?

**Comment by jonomango** [comment]
The thing is, we don't want to trigger an EPT violation. We want the guest to believe that they have successfully read or written to that page, but we don't want them to see the real contents of OUR page. Instead, the page that they are reading/writing to is a fake page that has garbage in it.

**Comment by LYingSiMon** [comment]
Thank you very much, I understand. I have another question, haha. I found that when using the EPT hook on the same physical page, the second hook will overwrite the results of the first hook, similar to the following situation:
```
VOID PrintLog()
{
	DbgPrintEx(0, 0, "hello %p |%d,%d \n", PrintLog, 1, 2);
}
VOID SystemThreadRoutine(PVOID Context)
{
	UNREFERENCED_PARAMETER(Context);

	KdPrintEx((0, 0, "[LyTest][%s] SystemThreadRoutine:%p \n", __FUNCTION__, SystemThreadRoutine));

	LARGE_INTEGER Interval;
	Interval.QuadPart = -10 * 1000 * 5000;

	while (!g_TerminateThread)
	{
		PrintLog();
		KeDelayExecutionThread(KernelMode, FALSE, &Interval);
	}

	PsTerminateSystemThread(STATUS_SUCCESS);
}
```

I'm trying to use EPT hook to make the DbgPrintEx in the code below print 4, 5 (instead of 1, 2). I'm using your code like this:

```
VOID LyHvEptCodePatchingByValue(ULONG_PTR Address, ULONG_PTR Value, ULONG Size)
{
    PVOID pAlign = PAGE_ALIGN(Address);
    PVOID pFakePage = ExAllocatePoolWithTag(NonPagedPool, PAGE_SIZE, LY_POOLTAG);
    if (!pFakePage)
        return;

    RtlCopyMemory(pFakePage, pAlign, PAGE_SIZE);
    RtlCopyMemory((PVOID)((ULONG_PTR)pFakePage + (Address & 0xFFF)), &Value, Size);

    for (size_t i = 0; i < KeQueryActiveProcessorCount(nullptr); ++i)
    {
        auto const orig_affinity = KeSetSystemAffinityThreadEx(1ull << i);

        hv::hypercall_input input;
        input.code = hv::hypercall_install_ept_hook;
        input.key = hv::hypercall_key;
        input.args[0] = MmGetPhysicalAddress(pAlign).QuadPart >> 12;
        input.args[1] = MmGetPhysicalAddress(pFakePage).QuadPart >> 12;

        hv::vmx_vmcall(input);

        KeRevertToUserAffinityThreadEx(orig_affinity);
    }
}
BOOLEAN TestEptHook()
{
    __debugbreak();

    ULONG_PTR Address1 = 0xFFFFF806413310A0 + 0x8;
    ULONG_PTR Address2 = 0xFFFFF806413310A0 + 0x10;
    LyHvEptCodePatchingByValue(Address1, 5, sizeof(UCHAR));
    LyHvEptCodePatchingByValue(Address2, 4, sizeof(UCHAR));

	return TRUE;
}
```
Unfortunately, I'm getting 4, 2 (instead of 4, 5). 
![image](https://github.com/jonomango/hv/assets/51651107/41851dcc-6c88-499f-9942-ca0c30bf30f4)

Please tell me how to fix this error, thank you.

**Comment by jonomango** [comment]
Yes that makes sense... the only real way to "fix" this would be to keep track of which pages have already been EPT hooked and to modify your hook code to reuse the previous page if it has already been hooked.
