### ISSUE TITLE
handle cr3

### ISSUE THREAD

**Issue by 1337331** [jonomango/hv#52]
https://github.com/jonomango/hv/blob/cd4d4022351b5d762045a02108973c697a79bb34/hv/exit-handlers.cpp#L487
thank you very much for open source such clean code
while I know this is not abide by with Intel sdm, is there a way to handle cr3 in another way?
when I read large amounts of data, `emulate_mov_to_cr3` is called very frequently.
caused my fps from 150+ to 50-

exclude other issue causing lower fps:
I have solved this but just c2p from other hv, code is not pretty so I didn't pull it.
https://github.com/jonomango/hv/issues/37

**Comment by jonomango** [comment]
Are you building as debug or as release? And what code did you use that improved performance?

**Comment by 1337331** [comment]
It finally got faster
![wJZwqjT3Jc](https://github.com/user-attachments/assets/f5cb82a0-9e84-45b7-89dd-f67fafc4ca17)

**Comment by jonomango** [comment]
FYI: You can set [this](https://github.com/jonomango/hv/blob/main/hv/vmcs.cpp#L29) to 0 if you aren't targeting an EAC game.

**Comment by 1337331** [comment]
> 仅供参考：如果您的目标不是 EAC 游戏，则可以将[其设置为 0。](https://github.com/jonomango/hv/blob/main/hv/vmcs.cpp#L29)

thanks perfect! you may close the issue

**Comment by 1337331** [comment]
> FYI: You can set [this](https://github.com/jonomango/hv/blob/main/hv/vmcs.cpp#L29) to 0 if you aren't targeting an EAC game.
Perfect!
thank you you can close the issue

**Comment by 1337331** [comment]
is there any other way to check if vmcall is available? SEH certainly has overhead.

**Comment by 1337331** [comment]
@jonomango 
<img width="185" alt="SddkRNUnpQ" src="https://github.com/user-attachments/assets/bd80a955-c54a-450d-abbb-46eeef2eb075">
AC is not EAC, but does that mean they messed with cr3?

**Comment by 1337331** [comment]
the physical address of function changed and there is no problem with allocated memory
<img width="488" alt="hK3YSliFyj" src="https://github.com/user-attachments/assets/aa8fcce8-b607-42c3-82a0-a46e5c70e4aa">
