### ISSUE TITLE
Stackwalking

### ISSUE THREAD

**Issue by 1337331** [jonomango/hv#58]
https://github.com/donnaskiez/nmi/blob/13c9e66911b9e7dd46c29fb3529e18963dfa1fdd/nmi-callback-handler/driver.c#L322
Not sure if I should post here, where should I handle Windows ISR?
I know it is possible to handle NMI, but there is also DPC/APC/IPI out there.
So I am trying to exclude hv memory range from stack.

https://github.com/jonomango/hv/blob/cd4d4022351b5d762045a02108973c697a79bb34/hv/vcpu.cpp#L331
other interrupts just "exception" in this function?

https://github.com/jonomango/hv/blob/cd4d4022351b5d762045a02108973c697a79bb34/hv/vcpu.cpp#L345
stack is copied from system for interrupts other than nmi?

Can I handle these in hv? I really don't want to guess if there are any unknown routines in Windows can interrupt all other programs without notification while my program is running and then get my stack.

maybe I need to call __sidt then modify then __lidt, hopefully this won't use too much cpu
before that I have to figure out which windows internal structures correspond to these for debug.

**Comment by lauralex** [comment]
I think you need to understand the notion of triple fault, which is handled incorrectly in jonomango code

**Comment by jonomango** [comment]
> https://github.com/donnaskiez/nmi/blob/13c9e66911b9e7dd46c29fb3529e18963dfa1fdd/nmi-callback-handler/driver.c#L322 Not sure if I should post here, where should I handle Windows ISR? I know it is possible to handle NMI, but there is also DPC/APC/IPI out there. So I am trying to exclude hv memory range from stack.
> 
> https://github.com/jonomango/hv/blob/cd4d4022351b5d762045a02108973c697a79bb34/hv/vcpu.cpp#L331
> 
> 
> other interrupts just "exception" in this function?
> https://github.com/jonomango/hv/blob/cd4d4022351b5d762045a02108973c697a79bb34/hv/vcpu.cpp#L345
> 
> 
> stack is copied from system for interrupts other than nmi?
> Can I handle these in hv? I really don't want to guess if there are any unknown routines in Windows can interrupt all other programs without notification while my program is running and then get my stack.
> 
> maybe I need to call __sidt then modify then __lidt, hopefully this won't use too much cpu before that I have to figure out which windows internal structures correspond to these for debug.

Sorry, I think you are confused. Interrupts are disabled when a vm-exit occurs. DPCs, APCs, IPIs are not relevent for this. That section of code is only there for unhandled host exceptions.

**Comment by lauralex** [comment]
It is just used to corrupt the host IDT to trigger a triple fault indirectly. That would freeze your system, and that's the reason some people might experience their so-called "freezes". Basically it means some exception is triggered at the host and since all the interrupt handlers (except for the nmi and the default exception handler for rdmsr) are dummy, when an unexpected exception happens, it would go to the default case with the r10 register probably clear and will trigger a triple fault through the host IDT corruption which would lead to the system freeze

**Comment by 1337331** [comment]
Thank you @lauralex for the detailed information, this is very useful.
If guest calling KeIpiGenericCall, won't interrupt pass hv?
Is this part not implemented due to complexity or is it just "transparent"?

**Comment by lauralex** [comment]
> Thank you @lauralex for the detailed information, this is very useful. For example if guest calling KeIpiGenericCall cause interrupt or other any interrupts, won't interrupt pass hv? Is this part not implemented due to complexity or is it just "transparent"?
> 
> For the specific question, well the title is already there. I assume hv can intercept the interrupt and gives blue team a fake machine frame.
> 
> https://github.com/jonomango/hv/blob/cd4d4022351b5d762045a02108973c697a79bb34/hv/interrupt-handlers.asm#L27
> 
> 
> If this is not feasible, maybe I have to do it in vmx non-root mode.
> That has nothing to do with hv itself. of course, I welcome anyone to discuss it with me.

Well, your question regarding possible interrupts happening during the vm-exit is valid. I don't think jonomango code handles external interrupts (for example, from the APIC) that happen exactly during vmx-root operation. So, I added a simple handler for all interrupts from 32-255 that simply injects them into the guest, just to be sure.

**Comment by lauralex** [comment]
Nevermind, I forgot that during a vm-exit the interrupt flag is disabled

**Comment by 1337331** [comment]
https://docs.hyperdbg.org/commands/extension-commands/interrupt
https://docs.hyperdbg.org/commands/extension-commands/exception
But how do they do it?

Anyway I did see that handling all interrupts would cause Windows to freeze.
I think I have to EPT hook where Windows make these interrupts and then fake IDT, and then resume IDT after callbacks ends.
